import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Caveat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import { ThemeShortcut } from "@/providers/theme-shortcut";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { ScrollToTop } from "@/components/ui/Scroll-to-top";
import { Navbar } from "@/components/hoc/Navbar";
import { Help } from "@/components/help/Help";
import { Suspense } from "react";

const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        nunitoSans.variable,
        caveat.variable,
      )}
    >
      <body className="min-h-full flex flex-col scrollbar-thin">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ScrollProgress />
          <ThemeShortcut />
          <Suspense>
            <Navbar />
          </Suspense>
          <Suspense>
            <ScrollToTop />
          </Suspense>
          {children}
          <Suspense>
            <Help />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
